#!/usr/bin/env python3
"""
  Prestack SEG-Y Amplitude Threshold Muting Tool

  Reads a prestack SEG-Y file, zeroes all samples whose absolute amplitude
  exceeds a user-defined threshold, and writes an output SEG-Y that is
  structurally identical to the input — same binary header, same text header,
  same trace order, same trace headers.  Only clipped sample values change.

  Configuration is read from config.py.  Do not edit this file for normal use.
  Author  : Beni
"""

import logging
import datetime
import json
import sys
from pathlib import Path
from typing import Optional, Dict, Any, List

import numpy as np
from tqdm import tqdm

try:
    import segyio
except ImportError:
    print("ERROR: segyio is not installed.  Run:  pip install segyio")
    sys.exit(1)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    from matplotlib.colors import Normalize
    HAS_MPL = True
except ImportError:
    HAS_MPL = False

# ─────────────────────────────────────────────────────────────────────────────
#  METADATA
# ─────────────────────────────────────────────────────────────────────────────

__version__ = "1.1.0"
__author__  = "Beni"


# ─────────────────────────────────────────────────────────────────────────────
#  LOGGING
# ─────────────────────────────────────────────────────────────────────────────

def setup_logging(output_dir: Path, log_level: int = logging.INFO) -> logging.Logger:
    """Dual-sink logger: DEBUG to file, INFO (or as configured) to console."""
    log_dir = output_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    fmt       = "[%(asctime)s] [%(levelname)-8s] %(message)s"
    datefmt   = "%Y-%m-%d %H:%M:%S"
    formatter = logging.Formatter(fmt, datefmt=datefmt)

    fh = logging.FileHandler(log_dir / "ampclip.log", encoding="utf-8")
    fh.setFormatter(formatter)
    fh.setLevel(logging.DEBUG)

    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(formatter)
    ch.setLevel(log_level)

    logger = logging.getLogger("AmpClip")
    logger.setLevel(logging.DEBUG)
    logger.addHandler(fh)
    logger.addHandler(ch)
    logger.propagate = False
    return logger


# ─────────────────────────────────────────────────────────────────────────────
#  OUTPUT DIRECTORY
# ─────────────────────────────────────────────────────────────────────────────

def create_output_dir(input_path: str) -> Path:
    """Create a timestamped output directory."""
    base = Path(input_path).stem
    ts   = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    out  = Path(f"{base}_AMPCLIP_{ts}")
    for sub in ("logs", "plots", "reports"):
        (out / sub).mkdir(parents=True, exist_ok=True)
    return out


# ─────────────────────────────────────────────────────────────────────────────
#  THRESHOLD ESTIMATION
# ─────────────────────────────────────────────────────────────────────────────

def estimate_threshold_from_percentile(
    input_path:      str,
    percentile:      float = 99.9,
    max_scan_traces: int   = 5000,
    logger:          Optional[logging.Logger] = None,
) -> float:
    """Return the amplitude value at `percentile` of |amplitude| over a trace subset."""
    log = logger or logging.getLogger("AmpClip")
    log.info(f"Estimating threshold: {percentile:.4f}th percentile "
             f"(scanning up to {max_scan_traces:,} traces)...")

    abs_values: List[np.ndarray] = []
    with segyio.open(str(input_path), ignore_geometry=True) as f:
        n    = f.tracecount
        step = max(1, n // max_scan_traces)
        for i in tqdm(range(0, n, step), desc="Scanning amplitudes",
                      unit="trace", ncols=80):
            abs_values.append(np.abs(f.trace[i]))

    threshold = float(np.percentile(np.concatenate(abs_values), percentile))
    log.info(f"  -> Threshold at {percentile:.4f}th percentile: {threshold:.6g}")
    return threshold


def estimate_threshold_from_rms_factor(
    input_path:      str,
    rms_factor:      float = 10.0,
    max_scan_traces: int   = 5000,
    logger:          Optional[logging.Logger] = None,
) -> float:
    """Return rms_factor * global_RMS computed over a trace subset."""
    log = logger or logging.getLogger("AmpClip")
    log.info(f"Estimating threshold: {rms_factor:.1f} x global RMS "
             f"(scanning up to {max_scan_traces:,} traces)...")

    sum_sq = 0.0
    n_samp = 0
    with segyio.open(str(input_path), ignore_geometry=True) as f:
        n    = f.tracecount
        step = max(1, n // max_scan_traces)
        for i in tqdm(range(0, n, step), desc="Scanning RMS",
                      unit="trace", ncols=80):
            tr      = f.trace[i].astype(np.float64)
            sum_sq += np.sum(tr ** 2)
            n_samp += len(tr)

    global_rms = float(np.sqrt(sum_sq / max(n_samp, 1)))
    threshold  = rms_factor * global_rms
    log.info(f"  Global RMS: {global_rms:.6g}")
    log.info(f"  -> Threshold ({rms_factor:.1f} x RMS): {threshold:.6g}")
    return threshold


# ─────────────────────────────────────────────────────────────────────────────
#  TAPER
# ─────────────────────────────────────────────────────────────────────────────

def _apply_taper(trace: np.ndarray, muted: np.ndarray, taper_samples: int) -> np.ndarray:
    """Apply a cosine taper on both sides of each contiguous muted cluster."""
    if taper_samples <= 0:
        return trace

    result = trace.copy()
    ns     = len(trace)
    taper  = 0.5 * (1.0 - np.cos(np.linspace(0, np.pi, taper_samples)))

    transitions = np.diff(muted.astype(int), prepend=0, append=0)
    starts = np.where(transitions ==  1)[0]
    ends   = np.where(transitions == -1)[0]

    for s, e in zip(starts, ends):
        for k in range(taper_samples):
            pre = s - taper_samples + k
            if 0 <= pre < ns:
                result[pre] *= taper[k]
            post = e + k
            if 0 <= post < ns:
                result[post] *= taper[taper_samples - 1 - k]

    return result


# ─────────────────────────────────────────────────────────────────────────────
#  STATISTICS ACCUMULATOR
# ─────────────────────────────────────────────────────────────────────────────

class AmpClipStats:
    """Accumulates per-run processing statistics."""

    def __init__(self):
        self.n_traces_total     = 0
        self.n_traces_affected  = 0
        self.n_samples_total    = 0
        self.n_samples_muted    = 0
        self.max_amplitude_in   = 0.0
        self.max_amplitude_out  = 0.0
        self.global_rms_in      = 0.0
        self.global_rms_out     = 0.0
        self.threshold          = 0.0
        self.taper_samples      = 0
        self._sum_sq_in         = 0.0
        self._sum_sq_out        = 0.0
        # per-trace muted sample count — used for QC plot
        self.muted_per_trace: List[int] = []

    def update(self, trace_in: np.ndarray, trace_out: np.ndarray,
               muted: np.ndarray):
        n     = len(trace_in)
        n_mut = int(muted.sum())
        self.n_samples_total += n
        self.n_samples_muted += n_mut
        self.muted_per_trace.append(n_mut)
        if n_mut > 0:
            self.n_traces_affected += 1
        pk_in = float(np.max(np.abs(trace_in)))
        if pk_in > self.max_amplitude_in:
            self.max_amplitude_in = pk_in
        pk_out = float(np.max(np.abs(trace_out)))
        if pk_out > self.max_amplitude_out:
            self.max_amplitude_out = pk_out
        self._sum_sq_in  += float(np.sum(trace_in.astype(np.float64)  ** 2))
        self._sum_sq_out += float(np.sum(trace_out.astype(np.float64) ** 2))

    def finalise(self):
        denom = max(self.n_samples_total, 1)
        self.global_rms_in  = float(np.sqrt(self._sum_sq_in  / denom))
        self.global_rms_out = float(np.sqrt(self._sum_sq_out / denom))


# ─────────────────────────────────────────────────────────────────────────────
#  CORE PROCESSING
# ─────────────────────────────────────────────────────────────────────────────

def clip_segy(
    input_path:    str,
    output_path:   str,
    threshold:     float,
    taper_samples: int  = 0,
    invert:        bool = False,
    logger:        Optional[logging.Logger] = None,
) -> AmpClipStats:
    """
    Core single-pass processing function.

    Parameters
    ----------
    input_path    : input SEG-Y path
    output_path   : output SEG-Y path
    threshold     : amplitude threshold; |x| > threshold -> zeroed (invert=False)
    taper_samples : cosine taper half-width in samples (0 = hard mute)
    invert        : if True, zero |x| < threshold instead
    logger        : logger instance

    Returns
    -------
    AmpClipStats
    """
    log   = logger or logging.getLogger("AmpClip")
    stats = AmpClipStats()
    stats.threshold     = threshold
    stats.taper_samples = taper_samples

    log.info("Opening input file...")

    with segyio.open(str(input_path), ignore_geometry=True) as src:

        n_traces = src.tracecount
        ns       = int(src.samples.size)
        dt_us    = float(segyio.dt(src))

        stats.n_traces_total = n_traces

        log.info(f"  Traces        : {n_traces:,}")
        log.info(f"  Samples/trace : {ns:,}")
        log.info(f"  Sample rate   : {dt_us:.1f} µs")
        log.info(f"  Threshold     : {threshold:.6g}  "
                 f"({'keep-large mode' if invert else 'mute-large mode'})")
        if taper_samples > 0:
            log.info(f"  Taper         : {taper_samples} samples each side "
                     f"({taper_samples * dt_us * 1e-3:.2f} ms)")
        else:
            log.info(f"  Taper         : none (hard zeroing)")

        log.info("Creating output SEG-Y (preserving full input structure)...")
        spec            = segyio.spec()
        spec.sorting    = None
        spec.format     = src.format
        spec.samples    = src.samples.copy()
        spec.tracecount = n_traces

        with segyio.create(str(output_path), spec) as dst:

            # Copy binary header
            dst.bin.update(tsort=src.bin[segyio.BinField.SortingCode])
            for k in src.bin.keys():
                try:
                    dst.bin.update(**{k: src.bin[k]})
                except Exception:
                    pass

            # Copy all text headers
            for i in range(len(src.text)):
                try:
                    dst.text[i] = src.text[i]
                except Exception:
                    pass

            # Process traces
            log.info("Processing traces...")
            for i in tqdm(range(n_traces), desc="Muting amplitudes",
                          unit="trace", ncols=90):

                trace_in  = src.trace[i].copy().astype(np.float32)
                abs_tr    = np.abs(trace_in)
                muted     = (abs_tr < threshold) if invert else (abs_tr > threshold)

                trace_out          = trace_in.copy()
                trace_out[muted]   = 0.0

                if taper_samples > 0 and muted.any():
                    trace_out = _apply_taper(trace_out, muted, taper_samples)

                stats.update(trace_in, trace_out, muted)

                dst.trace[i]  = trace_out
                dst.header[i] = src.header[i]

    stats.finalise()
    return stats


# ─────────────────────────────────────────────────────────────────────────────
#  VERIFICATION
# ─────────────────────────────────────────────────────────────────────────────

def verify_output(
    input_path:  str,
    output_path: str,
    threshold:   float,
    n_check:     int = 200,
    logger:      Optional[logging.Logger] = None,
) -> bool:
    """
    Spot-check output file:
      1. Trace and sample counts match input.
      2. No output sample exceeds the threshold (with IBM-float rounding margin).
      3. All trace header bytes are identical to input for sampled traces.
    """
    log = logger or logging.getLogger("AmpClip")
    log.info("Verifying output file...")
    ok = True

    # Build integer-only TraceField map once (avoids method-object TypeError)
    field_map: Dict[str, int] = {
        k: getattr(segyio.TraceField, k)
        for k in dir(segyio.TraceField)
        if not k.startswith("_")
        and isinstance(getattr(segyio.TraceField, k), int)
    }

    # IBM float32 -> IEEE float32 roundtrip can introduce up to ~0.03 % error.
    # We use a 0.1 % tolerance so genuine violations still surface.
    AMP_TOLERANCE = 1.001

    try:
        with segyio.open(str(input_path),  ignore_geometry=True) as src, \
             segyio.open(str(output_path), ignore_geometry=True) as dst:

            if src.tracecount != dst.tracecount:
                log.error(f"  [FAIL] Trace count mismatch: "
                          f"{src.tracecount} vs {dst.tracecount}")
                ok = False
            else:
                log.debug(f"  [OK]   Trace count: {src.tracecount:,}")

            if len(src.samples) != len(dst.samples):
                log.error(f"  [FAIL] Sample count mismatch: "
                          f"{len(src.samples)} vs {len(dst.samples)}")
                ok = False
            else:
                log.debug(f"  [OK]   Sample count: {len(src.samples):,}")

            n   = src.tracecount
            rng = np.random.default_rng(seed=42)
            idx = np.sort(rng.choice(n, size=min(n_check, n), replace=False))

            amp_violations    = 0
            header_mismatches = 0

            for i in tqdm(idx, desc="Verifying",
                          unit="trace", ncols=80, leave=False):

                # Amplitude check
                if np.any(np.abs(dst.trace[i]) > threshold * AMP_TOLERANCE):
                    amp_violations += 1

                # Header check — compare by integer byte position only
                h_in  = src.header[i]
                h_out = dst.header[i]
                for byte_pos in field_map.values():
                    try:
                        if h_in[byte_pos] != h_out[byte_pos]:
                            header_mismatches += 1
                            break
                    except Exception:
                        pass

            if amp_violations:
                log.error(f"  [FAIL] {amp_violations} traces contain "
                          f"amplitudes above threshold (tolerance {AMP_TOLERANCE:.3f}x).")
                ok = False
            else:
                log.info(f"  [OK]   Amplitude check passed on {len(idx)} sampled traces.")

            if header_mismatches:
                log.error(f"  [FAIL] {header_mismatches} traces have header mismatches.")
                ok = False
            else:
                log.info(f"  [OK]   Header check passed on {len(idx)} sampled traces.")

    except Exception as exc:
        log.error(f"  Verification raised an exception: {exc}")
        ok = False

    if ok:
        log.info("Verification PASSED.")
    else:
        log.warning("Verification FAILED — inspect the log for details.")

    return ok


# ─────────────────────────────────────────────────────────────────────────────
#  QC PLOTS
# ─────────────────────────────────────────────────────────────────────────────

_STYLE = {
    "fig_bg":    "#0d1117",
    "ax_bg":     "#161b22",
    "edge":      "#30363d",
    "text":      "#e6edf3",
    "muted":     "#8b949e",
    "primary":   "#58a6ff",
    "secondary": "#f0883e",
    "success":   "#3fb950",
    "danger":    "#f85149",
    "warning":   "#d29922",
}

def _apply_style():
    plt.rcParams.update({
        "figure.facecolor":  _STYLE["fig_bg"],
        "axes.facecolor":    _STYLE["ax_bg"],
        "axes.edgecolor":    _STYLE["edge"],
        "axes.labelcolor":   _STYLE["text"],
        "axes.titlecolor":   _STYLE["text"],
        "xtick.color":       _STYLE["muted"],
        "ytick.color":       _STYLE["muted"],
        "text.color":        _STYLE["text"],
        "grid.color":        "#21262d",
        "grid.linewidth":    0.5,
        "axes.grid":         True,
        "figure.dpi":        150,
        "savefig.dpi":       150,
        "savefig.bbox":      "tight",
        "savefig.facecolor": _STYLE["fig_bg"],
        "font.family":       "monospace",
        "axes.spines.top":   False,
        "axes.spines.right": False,
    })


def _save(fig: plt.Figure, path: Path):
    fig.savefig(path, dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.close(fig)


def make_qc_plots(
    input_path:  str,
    output_path: str,
    threshold:   float,
    stats:       AmpClipStats,
    plot_dir:    Path,
    n_traces:    int = 300,
    logger:      Optional[logging.Logger] = None,
):
    """
    Generate QC plots showing what the muting did:
      1. Seismic sections — input vs output side by side + difference
      2. Mute mask — where exactly samples were zeroed
      3. Per-trace muted sample count
      4. Amplitude histogram with threshold line
      5. RMS per trace — before and after
    """
    log = logger or logging.getLogger("AmpClip")

    if not HAS_MPL:
        log.warning("matplotlib not installed — skipping plots.")
        return

    _apply_style()
    log.info(f"Generating QC plots (up to {n_traces} traces)...")
    plot_dir.mkdir(parents=True, exist_ok=True)

    # ── Load a subset of traces from both files ───────────────────────────
    def _load_traces(path: str, n_max: int):
        with segyio.open(str(path), ignore_geometry=True) as f:
            total = f.tracecount
            ns    = f.samples.size
            dt    = float(segyio.dt(f))
            t     = f.samples / 1000.0  # ms
            step  = max(1, total // n_max)
            idx   = list(range(0, total, step))[:n_max]
            data  = np.zeros((len(idx), ns), dtype=np.float32)
            for ii, ti in enumerate(tqdm(idx, desc=f"Loading {Path(path).name}",
                                         unit="trace", ncols=80, leave=False)):
                data[ii] = f.trace[ti]
        return data, t, dt, idx, total

    log.info("  Loading input traces for plotting...")
    data_in,  t, dt_us, trace_idx, n_total = _load_traces(input_path,  n_traces)
    log.info("  Loading output traces for plotting...")
    data_out, _, _,      _,          _     = _load_traces(output_path, n_traces)

    n_plot, ns = data_in.shape
    data_diff  = data_in - data_out   # difference = what was removed

    # Mute mask for the loaded subset (True where amplitude was zeroed)
    mute_mask = (data_in != 0) & (data_out == 0)

    # ── Plot 1: Three-panel seismic comparison ────────────────────────────
    log.info("  Plotting seismic comparison (input / output / removed)...")
    fig = plt.figure(figsize=(22, 10))
    gs  = gridspec.GridSpec(1, 3, figure=fig, wspace=0.12)
    fig.suptitle(
        f"SEISMIC SECTION COMPARISON  |  threshold = {threshold:.4g}  |  "
        f"{stats.n_samples_muted:,} samples muted  ({stats.n_samples_muted/max(stats.n_samples_total,1)*100:.4f} %)",
        color=_STYLE["text"], fontsize=12, fontweight="bold",
    )

    vmax = float(np.percentile(np.abs(data_in), 98)) or 1.0

    panels = [
        (data_in,   "INPUT",           "RdBu_r", (-vmax,   vmax)),
        (data_out,  "OUTPUT (clipped)", "RdBu_r", (-vmax,   vmax)),
        (data_diff, "REMOVED",          "hot",    (0,       vmax * 0.2)),
    ]
    for col, (data, title, cmap, (vmin, vmx)) in enumerate(panels):
        ax = fig.add_subplot(gs[0, col])
        im = ax.imshow(
            data.T, aspect="auto", cmap=cmap,
            vmin=vmin, vmax=vmx,
            extent=[0, n_plot, t[-1], t[0]],
            interpolation="bilinear",
        )
        plt.colorbar(im, ax=ax, fraction=0.025, pad=0.02,
                     label="Amplitude")
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.set_xlabel("Trace index")
        if col == 0:
            ax.set_ylabel("Time (ms)")
        else:
            ax.set_yticklabels([])

    _save(fig, plot_dir / "01_seismic_comparison.png")

    # ── Plot 2: Mute mask ─────────────────────────────────────────────────
    log.info("  Plotting mute mask...")
    fig, axes = plt.subplots(1, 2, figsize=(18, 8))
    fig.suptitle("MUTE MASK  —  Zeroed sample locations",
                 color=_STYLE["text"], fontsize=12, fontweight="bold")

    # Variable density with mute mask overlaid
    ax = axes[0]
    ax.imshow(data_in.T, aspect="auto", cmap="RdBu_r",
              vmin=-vmax, vmax=vmax,
              extent=[0, n_plot, t[-1], t[0]],
              interpolation="bilinear", alpha=0.85)
    # Overlay muted samples in a vivid colour
    mask_rgba = np.zeros((*mute_mask.T.shape, 4), dtype=np.float32)
    mask_rgba[mute_mask.T, 0] = 1.0   # R
    mask_rgba[mute_mask.T, 3] = 0.85  # alpha
    ax.imshow(mask_rgba, aspect="auto",
              extent=[0, n_plot, t[-1], t[0]],
              interpolation="nearest")
    ax.set_title("Input section + muted samples (red)", fontsize=10)
    ax.set_xlabel("Trace index"); ax.set_ylabel("Time (ms)")

    # Binary mask only
    ax = axes[1]
    im = ax.imshow(mute_mask.T.astype(np.float32), aspect="auto",
                   cmap="inferno", vmin=0, vmax=1,
                   extent=[0, n_plot, t[-1], t[0]],
                   interpolation="nearest")
    plt.colorbar(im, ax=ax, fraction=0.025, pad=0.02,
                 label="Muted (1 = zeroed)")
    ax.set_title("Mute mask (binary)", fontsize=10)
    ax.set_xlabel("Trace index"); ax.set_ylabel("Time (ms)")

    fig.tight_layout()
    _save(fig, plot_dir / "02_mute_mask.png")

    # ── Plot 3: Per-trace muted sample count ──────────────────────────────
    log.info("  Plotting per-trace muted sample count...")
    muted_arr = np.array(stats.muted_per_trace)
    fig, axes = plt.subplots(2, 1, figsize=(18, 8), sharex=False)
    fig.suptitle("PER-TRACE MUTED SAMPLE COUNT",
                 color=_STYLE["text"], fontsize=12, fontweight="bold")

    x_all = np.arange(len(muted_arr))
    axes[0].bar(x_all, muted_arr, width=1.0, color=_STYLE["danger"],
                alpha=0.85, edgecolor="none")
    axes[0].set_xlabel("Trace index (all traces)")
    axes[0].set_ylabel("Muted samples")
    axes[0].set_title("All traces", fontsize=10)
    mean_v = muted_arr.mean()
    axes[0].axhline(mean_v, color=_STYLE["warning"], lw=1.2,
                    linestyle="--", label=f"mean = {mean_v:.1f}")
    axes[0].legend(fontsize=8)

    counts = muted_arr[muted_arr > 0]
    if len(counts):
        axes[1].hist(counts, bins=min(80, len(counts)),
                     color=_STYLE["secondary"], alpha=0.85, edgecolor="none")
        axes[1].set_xlabel("Muted samples per affected trace")
        axes[1].set_ylabel("Number of traces")
        axes[1].set_title("Distribution (affected traces only)", fontsize=10)
    else:
        axes[1].text(0.5, 0.5, "No traces affected",
                     transform=axes[1].transAxes, ha="center",
                     color=_STYLE["muted"], fontsize=12)

    fig.tight_layout()
    _save(fig, plot_dir / "03_per_trace_mute_count.png")

    # ── Plot 4: Amplitude histogram with threshold ────────────────────────
    log.info("  Plotting amplitude histogram...")
    flat_in  = data_in.flatten()
    flat_out = data_out.flatten()

    q01, q999 = np.percentile(np.abs(flat_in[flat_in != 0]), [0.1, 99.9])

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle("AMPLITUDE DISTRIBUTION  —  Input vs Output",
                 color=_STYLE["text"], fontsize=12, fontweight="bold")

    bins = np.linspace(
        np.percentile(flat_in, 0.1),
        np.percentile(flat_in, 99.9),
        200,
    )
    axes[0].hist(flat_in,  bins=bins, color=_STYLE["primary"],
                 alpha=0.6, edgecolor="none", label="Input",  density=True)
    axes[0].hist(flat_out, bins=bins, color=_STYLE["success"],
                 alpha=0.6, edgecolor="none", label="Output", density=True)
    axes[0].axvline( threshold, color=_STYLE["danger"], lw=1.5,
                    linestyle="--", label=f"threshold = +{threshold:.4g}")
    axes[0].axvline(-threshold, color=_STYLE["danger"], lw=1.5,
                    linestyle="--", label=f"threshold = -{threshold:.4g}")
    axes[0].set_xlabel("Amplitude"); axes[0].set_ylabel("Density")
    axes[0].set_title("Linear scale", fontsize=10)
    axes[0].legend(fontsize=8)

    # Log |amplitude|
    abs_in  = np.abs(flat_in[np.abs(flat_in)  > 1e-15])
    abs_out = np.abs(flat_out[np.abs(flat_out) > 1e-15])
    if len(abs_in) and len(abs_out):
        logbins = np.logspace(
            np.log10(min(abs_in.min(), abs_out.min())),
            np.log10(max(abs_in.max(), abs_out.max())),
            150,
        )
        axes[1].hist(abs_in,  bins=logbins, color=_STYLE["primary"],
                     alpha=0.6, edgecolor="none", label="Input",  density=True)
        axes[1].hist(abs_out, bins=logbins, color=_STYLE["success"],
                     alpha=0.6, edgecolor="none", label="Output", density=True)
        axes[1].axvline(threshold, color=_STYLE["danger"], lw=1.5,
                        linestyle="--", label=f"threshold = {threshold:.4g}")
        axes[1].set_xscale("log")
        axes[1].set_xlabel("|Amplitude|"); axes[1].set_ylabel("Density")
        axes[1].set_title("Log |amplitude| scale", fontsize=10)
        axes[1].legend(fontsize=8)

    fig.tight_layout()
    _save(fig, plot_dir / "04_amplitude_histogram.png")

    # ── Plot 5: RMS per trace — before / after ────────────────────────────
    log.info("  Plotting RMS per trace...")
    rms_in  = np.sqrt(np.mean(data_in  ** 2, axis=1))
    rms_out = np.sqrt(np.mean(data_out ** 2, axis=1))
    x_sub   = np.array(trace_idx)

    fig, axes = plt.subplots(2, 1, figsize=(18, 8), sharex=True)
    fig.suptitle("RMS AMPLITUDE PER TRACE  —  Input vs Output",
                 color=_STYLE["text"], fontsize=12, fontweight="bold")

    axes[0].plot(x_sub, rms_in,  color=_STYLE["primary"],
                 lw=0.6, alpha=0.9, label="Input RMS")
    axes[0].plot(x_sub, rms_out, color=_STYLE["success"],
                 lw=0.6, alpha=0.9, label="Output RMS")
    axes[0].set_ylabel("RMS Amplitude")
    axes[0].set_title("Absolute RMS", fontsize=10)
    axes[0].legend(fontsize=8)

    rms_diff_pct = np.where(
        rms_in > 1e-30,
        (rms_out - rms_in) / rms_in * 100,
        0.0,
    )
    axes[1].bar(x_sub, rms_diff_pct, width=max(1, n_total // n_plot),
                color=_STYLE["danger"], alpha=0.7, edgecolor="none")
    axes[1].axhline(0, color=_STYLE["muted"], lw=0.7)
    axes[1].set_xlabel("Trace index")
    axes[1].set_ylabel("RMS change (%)")
    axes[1].set_title("RMS change per trace (negative = amplitude reduced)", fontsize=10)

    fig.tight_layout()
    _save(fig, plot_dir / "05_rms_per_trace.png")

    log.info(f"  Plots written to: {plot_dir.resolve()}")


# ─────────────────────────────────────────────────────────────────────────────
#  REPORT
# ─────────────────────────────────────────────────────────────────────────────

def write_report(
    stats:       AmpClipStats,
    input_path:  str,
    output_path: str,
    output_dir:  Path,
    config:      Dict[str, Any],
    verified:    bool,
    logger:      Optional[logging.Logger] = None,
):
    """Write plain-text and JSON processing reports."""
    log = logger or logging.getLogger("AmpClip")
    ts  = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    pct_traces = stats.n_traces_affected / max(stats.n_traces_total, 1) * 100
    pct_samps  = stats.n_samples_muted   / max(stats.n_samples_total, 1) * 100
    rms_change = ((stats.global_rms_out - stats.global_rms_in)
                  / max(stats.global_rms_in, 1e-30) * 100)

    lines = [
        "=" * 72,
        "  AMPCLIP — Processing Report",
        f"  by Beni  |  {ts}",
        "=" * 72, "",
        "  FILES",
        "  " + "-" * 40,
        f"  Input          : {input_path}",
        f"  Output         : {output_path}",
        f"  Input size     : {Path(input_path).stat().st_size / 1e6:.2f} MB",
        f"  Output size    : {Path(output_path).stat().st_size / 1e6:.2f} MB",
        "",
        "  CONFIGURATION",
        "  " + "-" * 40,
    ]
    for k, v in config.items():
        lines.append(f"  {k:<28}: {v}")
    lines += [
        "",
        "  PROCESSING STATISTICS",
        "  " + "-" * 40,
        f"  Total traces         : {stats.n_traces_total:>12,}",
        f"  Affected traces      : {stats.n_traces_affected:>12,}   ({pct_traces:6.2f} %)",
        f"  Total samples        : {stats.n_samples_total:>12,}",
        f"  Muted samples        : {stats.n_samples_muted:>12,}   ({pct_samps:6.4f} %)",
        f"  Peak amplitude  [in] : {stats.max_amplitude_in:>18.6g}",
        f"  Peak amplitude [out] : {stats.max_amplitude_out:>18.6g}",
        f"  Global RMS      [in] : {stats.global_rms_in:>18.6g}",
        f"  Global RMS     [out] : {stats.global_rms_out:>18.6g}",
        f"  RMS change           : {rms_change:>+17.2f} %",
        "",
        "  VERIFICATION",
        "  " + "-" * 40,
        f"  Result: {'PASSED' if verified else 'FAILED  <-- check log'}",
        "",
        "=" * 72,
        "  AmpClip  —  by Beni",
        "=" * 72,
    ]

    report_dir = output_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    (report_dir / "ampclip_report.txt").write_text(
        "\n".join(lines), encoding="utf-8"
    )
    (report_dir / "ampclip_summary.json").write_text(
        json.dumps({
            "timestamp":            ts,
            "input_path":           str(input_path),
            "output_path":          str(output_path),
            "config":               config,
            "n_traces_total":       stats.n_traces_total,
            "n_traces_affected":    stats.n_traces_affected,
            "pct_traces_affected":  round(pct_traces, 4),
            "n_samples_total":      stats.n_samples_total,
            "n_samples_muted":      stats.n_samples_muted,
            "pct_samples_muted":    round(pct_samps, 6),
            "max_amplitude_in":     stats.max_amplitude_in,
            "max_amplitude_out":    stats.max_amplitude_out,
            "global_rms_in":        stats.global_rms_in,
            "global_rms_out":       stats.global_rms_out,
            "rms_change_pct":       round(rms_change, 4),
            "verification_passed":  verified,
        }, indent=2),
        encoding="utf-8",
    )

    log.info(f"Reports written to: {report_dir.resolve()}")

    print()
    print("─" * 56)
    print("  AmpClip — Summary")
    print("─" * 56)
    print(f"  Threshold        : {stats.threshold:.6g}")
    print(f"  Traces affected  : {stats.n_traces_affected:,} / "
          f"{stats.n_traces_total:,} ({pct_traces:.2f} %)")
    print(f"  Samples muted    : {stats.n_samples_muted:,} ({pct_samps:.4f} %)")
    print(f"  RMS change       : {rms_change:+.2f} %")
    print(f"  Verification     : {'PASSED' if verified else 'FAILED'}")
    print(f"  Output           : {Path(output_path).resolve()}")
    print("─" * 56)
    print()


# ─────────────────────────────────────────────────────────────────────────────
#  HIGH-LEVEL RUNNER
# ─────────────────────────────────────────────────────────────────────────────

def run(
    input_path:           str,
    threshold:            Optional[float] = None,
    output_path:          Optional[str]   = None,
    taper_samples:        int             = 0,
    invert:               bool            = False,
    verify:               bool            = True,
    make_plots:           bool            = True,
    plot_n_traces:        int             = 300,
    threshold_mode:       str             = "absolute",
    threshold_percentile: float           = 99.9,
    threshold_rms_factor: float           = 10.0,
    scan_traces:          int             = 5000,
    log_level:            int             = logging.INFO,
) -> str:
    """
    End-to-end processing pipeline.  All parameters mirror config.py.

    Returns
    -------
    str  —  absolute path to the output SEG-Y file.
    """
    out_dir = create_output_dir(input_path)
    logger  = setup_logging(out_dir, log_level=log_level)

    logger.info("=" * 66)
    logger.info(f"AMPCLIP v{__version__}  —  Amplitude Threshold Muting Tool")
    logger.info(f"Author: {__author__}")
    logger.info("=" * 66)
    logger.info(f"Input file : {Path(input_path).resolve()}")
    logger.info(f"Output dir : {out_dir.resolve()}")

    if not Path(input_path).exists():
        logger.error(f"Input file not found: {input_path}")
        raise FileNotFoundError(f"SEG-Y not found: {input_path}")

    logger.info(f"Input size : {Path(input_path).stat().st_size / 1e6:.2f} MB")

    # Determine threshold
    if threshold is None:
        if threshold_mode == "percentile":
            threshold = estimate_threshold_from_percentile(
                input_path, threshold_percentile, scan_traces, logger)
        elif threshold_mode == "rms":
            threshold = estimate_threshold_from_rms_factor(
                input_path, threshold_rms_factor, scan_traces, logger)
        else:
            raise ValueError(
                "THRESHOLD is None but THRESHOLD_MODE is 'absolute'. "
                "Either set THRESHOLD to a number, or change THRESHOLD_MODE "
                "to 'percentile' or 'rms' in config.py."
            )

    if threshold <= 0:
        raise ValueError(f"Threshold must be > 0, got {threshold}.")

    logger.info(f"Threshold  : {threshold:.6g}")

    # Determine output path
    if output_path is None:
        stem        = Path(input_path).stem
        suffix      = Path(input_path).suffix or ".sgy"
        output_path = str(out_dir / f"{stem}_ampclip{suffix}")

    logger.info(f"Output     : {Path(output_path).resolve()}")

    # Process
    stats = clip_segy(
        input_path    = input_path,
        output_path   = output_path,
        threshold     = threshold,
        taper_samples = taper_samples,
        invert        = invert,
        logger        = logger,
    )

    logger.info("Processing complete.")
    logger.info(f"  Affected traces : {stats.n_traces_affected:,} / {stats.n_traces_total:,}")
    logger.info(f"  Muted samples   : {stats.n_samples_muted:,} / {stats.n_samples_total:,}")
    logger.info(f"  Peak in / out   : {stats.max_amplitude_in:.4g} / "
                f"{stats.max_amplitude_out:.4g}")

    # Verify
    verified = False
    if verify:
        verified = verify_output(input_path, output_path, threshold, logger=logger)

    # Plots
    if make_plots:
        make_qc_plots(
            input_path  = input_path,
            output_path = output_path,
            threshold   = threshold,
            stats       = stats,
            plot_dir    = out_dir / "plots",
            n_traces    = plot_n_traces,
            logger      = logger,
        )

    # Report
    config_dict = {
        "threshold":              threshold,
        "threshold_mode":         threshold_mode,
        "taper_samples":          taper_samples,
        "invert":                 invert,
        "make_plots":             make_plots,
        "verify":                 verify,
        "version":                __version__,
    }
    write_report(stats, input_path, output_path, out_dir,
                 config_dict, verified, logger)

    return str(Path(output_path).resolve())


# ─────────────────────────────────────────────────────────────────────────────
#  ENTRY POINT  —  reads all settings from config.py
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    try:
        import config as cfg
    except ImportError:
        print("ERROR: config.py not found in the working directory.")
        print("       Copy config.py next to ampclip.py and edit it.")
        sys.exit(1)

    run(
        input_path           = cfg.INPUT_FILE,
        threshold            = cfg.THRESHOLD,
        output_path          = cfg.OUTPUT_FILE,
        taper_samples        = cfg.TAPER_SAMPLES,
        invert               = cfg.INVERT,
        verify               = cfg.VERIFY,
        make_plots           = cfg.MAKE_PLOTS,
        plot_n_traces        = cfg.PLOT_N_TRACES,
        threshold_mode       = cfg.THRESHOLD_MODE,
        threshold_percentile = cfg.THRESHOLD_PERCENTILE,
        threshold_rms_factor = cfg.THRESHOLD_RMS_FACTOR,
        scan_traces          = cfg.SCAN_TRACES,
        log_level            = cfg.LOG_LEVEL,
    )
